---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: boshcpi/gce-cpi-release
inputs:
  - name: bosh-cpi-src
outputs:
  - name: candidate
run:
  path: bosh-cpi-src/ci/pr/tasks/build-candidate.sh
