---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: boshcpi/gce-cpi-release
inputs:
  - name: bosh-cpi-src
  - name: stemcell
run:
  path: bosh-cpi-src/ci/tasks/run-int.sh

