---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: boshcpi/gce-cpi-release
inputs:
  - name: bosh-cpi-src
run:
  path: bosh-cpi-src/ci/tasks/teardown-infrastructure.sh
params:
  google_project:                 replace-me
  google_region:                  replace-me
  google_zone:                    replace-me
  google_json_key_data:           replace-me
  google_network:                 replace-me
  google_subnetwork:              replace-me
  google_firewall_internal:       replace-me
  google_firewall_external:       replace-me
  google_address_director_ubuntu: replace-me
  google_address_bats_ubuntu:     replace-me
  google_address_int_ubuntu:      replace-me
  google_service_account:         replace-me
  google_backend_service:         replace-me
  google_region_backend_service:  replace-me
