---
platform: linux
image_resource:
  type: docker-image
  source: {repository: boshcpi/cpi-certification}

inputs:
  - name: bosh-cpi-src
  - name: director-state
  - name: bosh-cli

params:
  BOSH_LOG_LEVEL: info

run:
  path: bosh-cpi-src/ci/tasks/teardown.sh
