---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: boshcpi/gce-cpi-release
inputs:
  - name: bosh-cpi-src
run:
  path: bosh-cpi-src/ci/tasks/unit-tests.sh
params:
  GO_VERSION: ""
