---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/os-image-stemcell-builder

inputs:
  - name: bosh-cpi-src
  - name: stemcell

outputs:
  - name: light-stemcell
  - name: raw-stemcell

run:
  path: bosh-cpi-src/ci/stemcell/light/tasks/build-light-stemcell.sh

params:
  BUCKET_NAME:  ""
