---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: boshcpi/gce-cpi-release

inputs:
  - name: deployment-state
  - name: bosh-cpi-src

run:
  path: bosh-cpi-src/ci/stemcell/light/tasks/destroy-skeletal.sh
